from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtCore import QPoint, QSize, Qt
from PyQt5.QtGui import QCursor
import qtawesome as qta

def closeButton():
    sys.exit()


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        MainWindow.setObjectName("MainWindow")

        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.screen = app.primaryScreen()
        self.winX = int((self.screen.size().width() / 2) - (self.width() / 2 - 200))
        self.winY = int((self.screen.size().height() / 2) - (self.height() / 2))
        self.move(self.winX, self.winY)

        self.oldPos = self.pos()

        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background: rgba(31,31,31);")

        self.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 801, 41))
        self.frame.setStyleSheet("background: rgb(31, 31, 31);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 121, 21))
        self.label.setStyleSheet("color: #FFF; font-size:16px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 111, 21))
        self.label_2.setStyleSheet("color:  rgb(17, 158, 15); font-size: 14px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(370, 10, 81, 21))
        self.label_3.setStyleSheet("color: #FFF; font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(460, 10, 91, 21))
        self.label_4.setStyleSheet("color:  rgb(230, 70, 41); font-size: 14px")
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, 40, 621, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(-1, -1, 311, 241))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(309, -1, 301, 241))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(0, 240, 611, 241))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 39, 181, 491))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toolBox = QtWidgets.QToolBox(self.frame_2)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 181, 491))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 181, 437))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 181, 437))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(-1, 539, 801, 201))
        self.openGLWidget.setObjectName("openGLWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName("menubar")
        self.menubar.setStyleSheet("color: #FFF; border-bottom: 2px solid #333; padding: 5px; font-size: 12px;")

        self.close_btn = QtWidgets.QPushButton(self.menubar)
        self.close_btn.setIcon(qta.icon('fa5s.times', color="#55D6BE"))
        self.close_btn.setIconSize(QSize(20, 20))
        self.close_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.close_btn.clicked.connect(closeButton)
        self.menubar.setCornerWidget(self.close_btn, QtCore.Qt.TopRightCorner)
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTrade = QtWidgets.QMenu(self.menubar)
        self.menuTrade.setObjectName("menuTrade")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuCharts = QtWidgets.QMenu(self.menubar)
        self.menuCharts.setObjectName("menuCharts")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuIndicators = QtWidgets.QMenu(self.menuTools)
        self.menuIndicators.setObjectName("menuIndicators")
        self.menuSentiment = QtWidgets.QMenu(self.menuTools)
        self.menuSentiment.setObjectName("menuSentiment")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionADX = QtWidgets.QAction(MainWindow)
        self.actionADX.setObjectName("actionADX")
        self.actionCCI = QtWidgets.QAction(MainWindow)
        self.actionCCI.setObjectName("actionCCI")
        self.actionDPO = QtWidgets.QAction(MainWindow)
        self.actionDPO.setObjectName("actionDPO")
        self.actionMACD = QtWidgets.QAction(MainWindow)
        self.actionMACD.setObjectName("actionMACD")
        self.actionKST_Osc = QtWidgets.QAction(MainWindow)
        self.actionKST_Osc.setObjectName("actionKST_Osc")
        self.actionMI = QtWidgets.QAction(MainWindow)
        self.actionMI.setObjectName("actionMI")
        self.actionTrix = QtWidgets.QAction(MainWindow)
        self.actionTrix.setObjectName("actionTrix")
        self.actionVI = QtWidgets.QAction(MainWindow)
        self.actionVI.setObjectName("actionVI")
        self.actionMFI = QtWidgets.QAction(MainWindow)
        self.actionMFI.setObjectName("actionMFI")
        self.actionRSI = QtWidgets.QAction(MainWindow)
        self.actionRSI.setObjectName("actionRSI")
        self.actionStock_Osc = QtWidgets.QAction(MainWindow)
        self.actionStock_Osc.setObjectName("actionStock_Osc")
        self.actionTSI = QtWidgets.QAction(MainWindow)
        self.actionTSI.setObjectName("actionTSI")
        self.actionUlt_Osc = QtWidgets.QAction(MainWindow)
        self.actionUlt_Osc.setObjectName("actionUlt_Osc")
        self.actionWialliams_R = QtWidgets.QAction(MainWindow)
        self.actionWialliams_R.setObjectName("actionWialliams_R")
        self.actionAcc_Dist_Index = QtWidgets.QAction(MainWindow)
        self.actionAcc_Dist_Index.setObjectName("actionAcc_Dist_Index")
        self.actionOBV = QtWidgets.QAction(MainWindow)
        self.actionOBV.setObjectName("actionOBV")
        self.actionVPT = QtWidgets.QAction(MainWindow)
        self.actionVPT.setObjectName("actionVPT")
        self.actionATR = QtWidgets.QAction(MainWindow)
        self.actionATR.setObjectName("actionATR")
        self.actionKC = QtWidgets.QAction(MainWindow)
        self.actionKC.setObjectName("actionKC")
        self.actionStd_Dev = QtWidgets.QAction(MainWindow)
        self.actionStd_Dev.setObjectName("actionStd_Dev")
        self.actionMcClellan_Osc = QtWidgets.QAction(MainWindow)
        self.actionMcClellan_Osc.setObjectName("actionMcClellan_Osc")
        self.actionGoogle = QtWidgets.QAction(MainWindow)
        self.actionGoogle.setObjectName("actionGoogle")
        self.actionYahoo = QtWidgets.QAction(MainWindow)
        self.actionYahoo.setObjectName("actionYahoo")
        self.actionBing = QtWidgets.QAction(MainWindow)
        self.actionBing.setObjectName("actionBing")
        self.actionBuy = QtWidgets.QAction(MainWindow)
        self.actionBuy.setObjectName("actionBuy")
        self.actionSell = QtWidgets.QAction(MainWindow)
        self.actionSell.setObjectName("actionSell")
        self.actionShort = QtWidgets.QAction(MainWindow)
        self.actionShort.setObjectName("actionShort")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuTrade.addAction(self.actionBuy)
        self.menuTrade.addAction(self.actionSell)
        self.menuTrade.addAction(self.actionShort)
        self.menuIndicators.addAction(self.actionADX)
        self.menuIndicators.addAction(self.actionCCI)
        self.menuIndicators.addAction(self.actionDPO)
        self.menuIndicators.addAction(self.actionMACD)
        self.menuIndicators.addAction(self.actionKST_Osc)
        self.menuIndicators.addAction(self.actionMI)
        self.menuIndicators.addAction(self.actionTrix)
        self.menuIndicators.addAction(self.actionVI)
        self.menuIndicators.addAction(self.actionMFI)
        self.menuIndicators.addAction(self.actionRSI)
        self.menuIndicators.addAction(self.actionStock_Osc)
        self.menuIndicators.addAction(self.actionTSI)
        self.menuIndicators.addAction(self.actionUlt_Osc)
        self.menuIndicators.addAction(self.actionWialliams_R)
        self.menuIndicators.addAction(self.actionAcc_Dist_Index)
        self.menuIndicators.addAction(self.actionOBV)
        self.menuIndicators.addAction(self.actionVPT)
        self.menuIndicators.addAction(self.actionATR)
        self.menuIndicators.addAction(self.actionKC)
        self.menuIndicators.addAction(self.actionStd_Dev)
        self.menuIndicators.addAction(self.actionMcClellan_Osc)
        self.menuSentiment.addAction(self.actionGoogle)
        self.menuSentiment.addAction(self.actionYahoo)
        self.menuSentiment.addAction(self.actionBing)
        self.menuTools.addAction(self.menuIndicators.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuSentiment.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTrade.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuCharts.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        painter = QtGui.QPainter(self.menubar)
        painter.drawText(100, 100, "Hello!!!!!!")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GOOG 1,452.56"))
        self.label_2.setText(_translate("MainWindow", "+18.66(+1.30%)"))
        self.label_3.setText(_translate("MainWindow", "XOM 64.65"))
        self.label_4.setText(_translate("MainWindow", "-0.09(-0.14%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTrade.setTitle(_translate("MainWindow", "Trade"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuCharts.setTitle(_translate("MainWindow", "Charts"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuIndicators.setTitle(_translate("MainWindow", "Indicators"))
        self.menuSentiment.setTitle(_translate("MainWindow", "Sentiment"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionADX.setText(_translate("MainWindow", "ADX"))
        self.actionCCI.setText(_translate("MainWindow", "CCI"))
        self.actionDPO.setText(_translate("MainWindow", "DPO"))
        self.actionMACD.setText(_translate("MainWindow", "MACD"))
        self.actionKST_Osc.setText(_translate("MainWindow", "KST Osc"))
        self.actionMI.setText(_translate("MainWindow", "MI"))
        self.actionTrix.setText(_translate("MainWindow", "Trix"))
        self.actionVI.setText(_translate("MainWindow", "VI"))
        self.actionMFI.setText(_translate("MainWindow", "MFI"))
        self.actionRSI.setText(_translate("MainWindow", "RSI"))
        self.actionStock_Osc.setText(_translate("MainWindow", "Stock Osc"))
        self.actionTSI.setText(_translate("MainWindow", "TSI"))
        self.actionUlt_Osc.setText(_translate("MainWindow", "Ult Osc"))
        self.actionWialliams_R.setText(_translate("MainWindow", "Wialliams R"))
        self.actionAcc_Dist_Index.setText(_translate("MainWindow", "ADI"))
        self.actionOBV.setText(_translate("MainWindow", "OBV"))
        self.actionVPT.setText(_translate("MainWindow", "VPT"))
        self.actionATR.setText(_translate("MainWindow", "ATR"))
        self.actionKC.setText(_translate("MainWindow", "KC"))
        self.actionStd_Dev.setText(_translate("MainWindow", "Std Dev"))
        self.actionMcClellan_Osc.setText(_translate("MainWindow", "McClellan Osc"))
        self.actionGoogle.setText(_translate("MainWindow", "Google"))
        self.actionYahoo.setText(_translate("MainWindow", "Yahoo"))
        self.actionBing.setText(_translate("MainWindow", "Bing"))
        self.actionBuy.setText(_translate("MainWindow", "Buy"))
        self.actionSell.setText(_translate("MainWindow", "Sell"))
        self.actionShort.setText(_translate("MainWindow", "Short"))
        self.actionNew.setText(_translate("MainWindow", "New"))

    def ticker(self, event):
        painter = QtGui.QPainter(self.menuFile)
        painter.setPen(QtGui.QPen(QtCore.Qt.black, 10, QtCore.Qt.SolidLine))
        painter.drawText(100, 100, "HELLO WORLD!!!!!")

    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def mouseMoveEvent(self, event):
        delta = QPoint(event.globalPos() - self.oldPos)
        self.move(self.x() + delta.x(), self.y() + delta.y())
        self.oldPos = event.globalPos()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    MainWindow.show()
    sys.exit(app.exec_())
